In [1]:
import numpy
import math

In [17]:
N=6
A = numpy.zeros([N,N])

for i in range(N):
    A[i,i] = 4.
    if i > 0:
        A[i,i-1]=-1
    if i < N-1:
        A[i,i+1]=-1

d = [2, 3, 5, 9, 8, 6]


xp = numpy.linalg.solve(A, d)
        
print A
print d
print xp

[[ 4. -1.  0.  0.  0.  0.]
 [-1.  4. -1.  0.  0.  0.]
 [ 0. -1.  4. -1.  0.  0.]
 [ 0.  0. -1.  4. -1.  0.]
 [ 0.  0.  0. -1.  4. -1.]
 [ 0.  0.  0.  0. -1.  4.]]
[2, 3, 5, 9, 8, 6]
[ 0.90690484  1.62761937  2.60357266  3.78667125  3.54311233  2.38577808]


In [22]:
def thomassolve(a,b,c,d):
    
    n = len(b)
    
    cth = numpy.empty([n-1], dtype=float)
    dth = numpy.empty([n], dtype=float)
    xth = numpy.empty([n], dtype=float)
    
    cth[0] = c[0]/b[0]
    dth[0] = d[0]/b[0]
    
    for i in range(1,n-1):
        cth[i] = c[i]/(b[i]-cth[i-1]*a[i-1])
    for i in range(1,n):
        dth[i] = (d[i]-dth[i-1]*a[i-1])/(b[i]-cth[i-1]*a[i-1])
    
    xth[n-1] = dth[n-1]
    
    for i in range(n-2,-1,-1):
        xth[i] = dth[i]-cth[i]*xth[i+1]
    
    return xth
    
    

In [23]:
a = numpy.empty([N], dtype=float)
b = numpy.empty([N-1], dtype=float)
a[:] = 4
b[:] = -1

x = thomassolve(b,a,b,d)

print a
print b
print d
print
print x
print
print xp

[ 4.  4.  4.  4.  4.  4.]
[-1. -1. -1. -1. -1.]
[2, 3, 5, 9, 8, 6]

[ 0.90690484  1.62761937  2.60357266  3.78667125  3.54311233  2.38577808]

[ 0.90690484  1.62761937  2.60357266  3.78667125  3.54311233  2.38577808]
